## Part 1: Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [3]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [5]:
# Create a list of at least 10 column names to use as X data
x = ['Age', 'DistanceFromHome', 'Education', 'OverTime', 'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany', 'JobSatisfaction', 'NumCompaniesWorked', 'YearsSinceLastPromotion']

# Create X_df using your selected columns
X_df = attrition_df[x]

# Show the data types for X_df
X_df.dtypes


Age                         int64
DistanceFromHome            int64
Education                   int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
JobSatisfaction             int64
NumCompaniesWorked          int64
YearsSinceLastPromotion     int64
dtype: object

In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

In [7]:
# Convert the 'OverTime' column to numeric values
X_train['OverTime'].replace({'Yes': 1, 'No': 0}, inplace=True)
X_test['OverTime'].replace({'Yes': 1, 'No': 0}, inplace=True)

# Convert your X data to numeric data types however you see fit
X_train = X_train.astype(float)
X_test = X_test.astype(float)

# Add new code cells as necessary
X_train.tail() 

/var/folders/v3/3x37jm396m15n05th_799pjw0000gn/T/ipykernel_44706/2699069615.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train['OverTime'].replace({'Yes': 1, 'No': 0}, inplace=True)
/var/folders/v3/3x37jm396m15n05th_799pjw0000gn/T/ipykernel_44706/2699069615.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_down

Age  DistanceFromHome  Education  OverTime  StockOptionLevel  \
1130  35.0              28.0        3.0       0.0               2.0   
1294  41.0               5.0        3.0       0.0               0.0   
860   22.0               3.0        4.0       1.0               1.0   
1459  29.0              13.0        2.0       1.0               1.0   
1126  50.0               9.0        3.0       1.0               1.0   

      WorkLifeBalance  YearsAtCompany  JobSatisfaction  NumCompaniesWorked  \
1130              2.0            10.0              3.0                 1.0   
1294              1.0             3.0              2.0                 3.0   
860               3.0             0.0              4.0                 0.0   
1459              3.0             4.0              2.0                 4.0   
1126              3.0             1.0              3.0                 4.0   

      YearsSinceLastPromotion  
1130                      6.0  
1294                      1.0  
860                       0.0  
1459                      0.0  
1126                      0.0

In [90]:
y_train

Attrition              Department
1097        No  Research & Development
727         No  Research & Development
254         No                   Sales
1175        No  Research & Development
1341        No  Research & Development
...        ...                     ...
1130        No  Research & Development
1294        No  Research & Development
860        Yes  Research & Development
1459        No  Research & Development
1126        No                   Sales

[1176 rows x 2 columns]

In [125]:
#Scale the data
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# #convert the scaled data back to a DataFrame
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns)


In [120]:
X_test_scaled

array([[-0.95377387, -0.52269928,  0.09993302, ..., -1.58233648,
        -1.05916816, -0.35524399],
       [ 1.76363593,  0.45884859, -0.86335572, ..., -1.58233648,
        -0.65943075, -0.35524399],
       [-1.38855944,  1.56308993, -1.82664446, ...,  0.24111056,
        -0.65943075, -0.67610953],
       ...,
       [ 1.43754676,  2.29925083,  0.09993302, ..., -1.58233648,
         0.53978146, -0.35524399],
       [ 0.02449366,  0.09076814, -0.86335572, ...,  1.15283407,
         0.14004406, -0.67610953],
       [ 1.11145758, -0.89077972, -0.86335572, ...,  1.15283407,
        -1.05916816,  1.56994925]])

In [100]:
y_train[['Department']]

Department
1097  Research & Development
727   Research & Development
254                    Sales
1175  Research & Development
1341  Research & Development
...                      ...
1130  Research & Development
1294  Research & Development
860   Research & Development
1459  Research & Development
1126                   Sales

[1176 rows x 1 columns]

In [101]:
y_test[['Department']]

Department
1041                   Sales
184   Research & Development
1222         Human Resources
67    Research & Development
220   Research & Development
...                      ...
567                    Sales
560   Research & Development
945   Research & Development
522   Research & Development
651                    Sales

[294 rows x 1 columns]

In [129]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
dept_encoded = dept_encoder.fit_transform(y_train[['Department']])
# Convert the encoded data to a DataFrame
dept_encoded = pd.DataFrame(dept_encoded, columns=dept_encoder.get_feature_names_out(['Department']))

# Create two new variables by applying the encoder
# to the training and testing data
encoded_dept_train = dept_encoder.transform(y_train[['Department']])
encoded_dept_test = dept_encoder.transform(y_test[['Department']])

y_dept = pd.DataFrame(encoded_dept_train, columns=dept_encoder.get_feature_names_out(['Department']))



In [105]:
encoded_dept_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
encoded_dept_test[0:5]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [130]:
# Create a OneHotEncoder for the Department column
attr_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attr_encoded = attr_encoder.fit_transform(y_train[['Attrition']])
# Convert the encoded data to a DataFrame
attr_encoded = pd.DataFrame(dept_encoded, columns=dept_encoder.get_feature_names_out(['Department']))

# Create two new variables by applying the encoder
# to the training and testing data
encoded_attr_train = attr_encoder.transform(y_train[['Attrition']])
encoded_attr_test = attr_encoder.transform(y_test[['Attrition']])

y_attr = pd.DataFrame(encoded_attr_train, columns=attr_encoder.get_feature_names_out(['Attrition']))

In [123]:
encoded_attr_test[0:5]
  

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [124]:
encoded_attr_train


array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

## Part 2: Create, Compile, and Train the Model

In [111]:
# Find the number of columns in the X training data.
n_cols = X_train_scaled.shape[1]
# Create the input layer
input_layer = layers.Input(shape=(n_cols,))

# Create at least two shared layers
shared1 = layers.Dense(64, activation='relu')(input_layer)
shared2 = layers.Dense(128, activation='relu')(shared1)

# Create the output layer
output_layer = layers.Dense(2, activation='softmax')(shared2)

In [112]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden = layers.Dense(32, activation='relu')(shared2)

# Create the output layer
dept_output = layers.Dense(3, activation='softmax')(dept_hidden)


In [113]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attr_hidden = layers.Dense(32, activation='relu')(shared2)

# Create the output layer
attr_output = layers.Dense(2, activation='softmax')(attr_hidden)



In [115]:
# Create the model

model = Model(inputs=input_layer, outputs=[attr_output, dept_output])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Summarize the model
model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 10)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_21 (Dense)    │ (None, 64)        │        704 │ input_layer_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_22 (Dense)    │ (None, 128)       │      8,320 │ dense_21[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_26 (Dense)    │ (None, 32)        │      4,128 │ dense_22[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_24 (Dense)    │ (None, 32)        │      4,128 │ dense_22[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_27 (Dense)    │ (None, 2)         │         66 │ dense_26[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_25 (Dense)    │ (None, 3)         │         99 │ dense_24[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [138]:
# Train the model

model.fit(X_train_scaled, [encoded_dept_train, encoded_attr_train], epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10


ValueError: Attr 'Toutput_types' of 'OptionalFromValue' Op passed list of length 0 less than minimum 1.

In [19]:
# Evaluate the model with the testing data


In [20]:
# Print the accuracy for both department and attrition


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. 
2. 
3. 